TRANSLATIONS['en']['add_cloudstead'] = {
	title_create: "Create new Cloudstead",
	title_update: "Update Cloudstead",
	cloudstead_name: "Name",
	launch_config: "Launch Config",
	new_config: "New Config",
	cloud_config: "Cloud Config",
	new_cloud: "New Cloud",
	region: "Region",
	instance_types: "Instance Types",
	ssh_key: "SSH Keys",
	new_ssh: "New SSH Key",
	manage_ssh: "Manage SSH Keys",
	launch: "Launch",
	update: "Update",
	cancel: "Cancel",
};
