# Normally, things in {{CURLIES}} will be read from the process environment when the server starts up
#
# The environment for this app is set programmatically in LaunchApi.java
# From the environment that started this process, only ASSETS_DIR and API_PORT will be used here.
# The other values are determined at server startup time.
#
# Instead, the only variables defined by LaunchApi are:
#
#  HOME  a home directory for the user. if running in a sandboxed environment (from mac app store), this
#         should be a safe sandboxed (app-writeable) directory
#
#  DB_DATA_DIR  directory where database files will be stored, typically somewhere under HOME
#
#  LAUNCHER_ASSETS_DIR  if defined in the process environment, the value is still available here. Otherwise this is empty
#
#  LAUNCHER_PORT  if defined in the process environment, the value is still available here. Otherwise this is 0 (pick a random port)
#

serverName: cloudos-launcher

publicUriBase: http://127.0.0.1

database:
  driver: org.h2.Driver
  url: jdbc:h2:{{DB_DATA_DIR}}
  user: launcher
  password:

  hibernate:
    entityPackages: [ cloudos.launcher.model ]
    dialect: org.hibernate.dialect.H2Dialect
    showSql: true
    hbm2ddlAuto: update
    validationMode: ddl

staticAssets:
  baseUri: /
  assetRoot: web/
  localOverride: {{LAUNCHER_ASSETS_DIR}}
  mustacheCacheEnabled: false
  mustacheResourceRoot: web/
  utilPaths:
    INDEX_PATH: /index.html
    INDEX_ALIASES: /
    LOCALIZE: /localize

http:
  # if empty, a random port will be used
  port: {{LAUNCHER_PORT}}
  baseUri: /api

jersey:
  resourcePackages: [ cloudos.launcher.resources, org.cobbzilla.wizard.server, org.cobbzilla.wizard.filters ]
  responseFilters: [ org.cobbzilla.wizard.filters.ScrubbableScrubber ]
