  /* generated by ./bin/prep_dist.sh on Mon Jun 29 18:17:48 PDT 2015 */
  APPS = {
    init: {}, system: {}, cloudos: {}, app: {}
  };
  
  APPS.system.apache="apache";
  APPS.system.auth="auth";
  APPS.init.base="base";
  APPS.cloudos.cloudos="cloudos";
  APPS.cloudos.cloudos_dns="cloudos-dns";
  APPS.app.discourse="discourse";
  APPS.init.djbdns="djbdns";
  APPS.app.dokuwiki="dokuwiki";
  APPS.system.email="email";
  APPS.app.errbit="errbit";
  APPS.app.etherpad="etherpad";
  APPS.system.git="git";
  APPS.app.gitlab="gitlab";
  APPS.system.java="java";
  APPS.app.jira="jira";
  APPS.app.kanban="kanban";
  APPS.app.kandan="kandan";
  APPS.system.kestrel="kestrel";
  APPS.app.limesurvey="limesurvey";
  APPS.system.mysql="mysql";
  APPS.app.openemm="openemm";
  APPS.app.owa="owa";
  APPS.app.owncloud="owncloud";
  APPS.app.phabricator="phabricator";
  APPS.app.phplist="phplist";
  APPS.app.piwik="piwik";
  APPS.system.postgresql="postgresql";
  APPS.app.roundcube="roundcube";
  APPS.app.roundcube_addressbook="roundcube-addressbook";
  APPS.app.roundcube_calendar="roundcube-calendar";
  APPS.app.wordpress="wordpress";
